services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    entrypoint: ./entrypoint.sh
    command: "rails s -b 0.0.0.0"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
    env_file:
      - .env

  esbuild:
    build:
      context: .
    command: "node esbuild.config.js --watch"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - app

  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  bundle:
  pgdata:
