services:
  app:
    build: .
    working_dir: /app
    ports:
      - 3000:3000
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
  rubygems: